### ISSUE TITLE
[Feature Request] Generate schema.graphql from endpoint

### ISSUE THREAD

**Issue by MisterJimson** [blacksaltIT/dart_graphql#1]
Hello. Super cool project. Wondering if there is a way, or could be a way, to generate a schema.graphql file from an endpoint using a similar process to what you did here.

I have use cases for using the schema.graphql for other tools and it would also be a great way to track changes in the API over time if you checked it into source.

And by schema.graphql I specifically mean a file like this: https://github.com/marmelab/GraphQL-example/blob/master/schema.graphql

**Comment by janosroden** [comment]
Hello @MisterJimson, sorry for the delay, I didn't get notification about your issue.
I'm afraid your request is out of scope of this project. We focus only the last three items in this chain: GraphQL scheme -> Endpoint -> Client -> req/res.
However I found a project which maybe fits your needs: https://github.com/prisma-labs/get-graphql-schema

Best regards,
Janos
